{% set name = "archive_goate" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    git_url: https://github.com/marcoralab/archiving.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - 
    - pandas

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"
  entry_points:
    - archive_goate = archive_minerva:main
  script_env:
    - VERSION
    - CONDA_BLD_PATH

test:
  imports:
    - archive_goate

about:
  home: https://github.com/BEFH/flippyr
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'This package is an automated archiving script for the Goate and Marcora labs.'
  description: |
    Using DSMC to back up files is somewhat compled and it's difficult to track
    what files and directories have been archived in the lab. This script automates
    the process of archiving, stores information about the archive, and stores info
    across users for the entire lab.
  doc_url: https://github.com/marcoralab/archiving

extra:
  recipe-maintainers:
    - BEFH
